<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasApiTokens;

    protected $fillable = [
        'name',
        'email',
        'phone',
        'password',
        'role',                 // Role do usuário (user/admin)
        'referral_code',
        'referred_by',
        'balance',              // Saldo investido (usado para comprar pacotes)
        'balance_withdrawn',    // Saldo disponível para saque
        'total_invested',
        'total_earned',
        'total_withdrawn',
        'is_active',
        'is_verified',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'balance' => 'decimal:2',              // Saldo investido
            'balance_withdrawn' => 'decimal:2',    // Saldo para saque
            'total_invested' => 'decimal:2',
            'total_earned' => 'decimal:2',
            'total_withdrawn' => 'decimal:2',
            'is_active' => 'boolean',
            'is_verified' => 'boolean',
        ];
    }

    /**
     * Get the user who referred this user
     */
    public function referrer(): BelongsTo
    {
        return $this->belongsTo(User::class, 'referred_by');
    }

    /**
     * Get users referred by this user
     */
    public function referrals(): HasMany
    {
        return $this->hasMany(User::class, 'referred_by');
    }

    /**
     * Get user's investment cycles
     */
    public function cycles(): HasMany
    {
        return $this->hasMany(Cycle::class);
    }

    /**
     * Get commissions received by this user
     */
    public function commissionsReceived(): HasMany
    {
        return $this->hasMany(Commission::class, 'user_id');
    }

    /**
     * Get commissions generated by this user's purchases
     */
    public function commissionsGenerated(): HasMany
    {
        return $this->hasMany(Commission::class, 'from_user_id');
    }
}
